name: moowatermark
author: magicweb
category: Interface
tags: [watermark, input, hint]
docs: http://www.magicwebsolutions.co.uk/demos/home.action?demo=watermark
demo: http://www.magicwebsolutions.co.uk/demos/home.action?demo=watermark